package ru.profitsw2000.core.utils.constants

const val DATE_TIME_DATA_INTERVAL_MS = 500L
const val DATA_EXCHANGE_INTERVAL = 4
const val BLUETOOTH_INPUT_STREAM_READ_TIMEOUT = 10L
const val RING_BUFFER_BYTE_PARSING_PERIOD = 5L