package ru.profitsw2000.core.utils.constants

const val TEN_MINUTES_FRAME_FACTOR = 1
const val THIRTY_MINUTES_FRAME_FACTOR = TEN_MINUTES_FRAME_FACTOR*3
const val ONE_HOUR_FRAME_FACTOR = TEN_MINUTES_FRAME_FACTOR*6
const val TWO_HOURS_FRAME_FACTOR = ONE_HOUR_FRAME_FACTOR*2
const val FOUR_HOURS_FRAME_FACTOR = ONE_HOUR_FRAME_FACTOR*4
const val EIGHT_HOURS_FRAME_FACTOR = ONE_HOUR_FRAME_FACTOR*8
const val TWELVE_HOURS_FRAME_FACTOR = ONE_HOUR_FRAME_FACTOR*12
const val ONE_DAY_FRAME_FACTOR = ONE_HOUR_FRAME_FACTOR*24
const val ONE_WEEK_FRAME_FACTOR = ONE_DAY_FRAME_FACTOR*7
const val ONE_MONTH_FRAME_FACTOR = ONE_DAY_FRAME_FACTOR*30